### ISSUE TITLE
O-asteroid needs ResizeObserver

### ISSUE THREAD

**Issue by tomByrer** [zankhq/epicstudio#2]
I refreshed, then resized window.  Brave Win10
![image](https://github.com/zankhq/epicstudio/assets/1308419/64c0033a-0c81-4516-bba8-6554624de37e)

I'd fix it myself, but I plan to write my own hero UI to replace this regardless.
(Using your theme for the cool transitions.)

Clue: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

FYI only: no action needed; close as you wish

**Comment by zanhk** [comment]
Hi @tomByrer, thanks for the segnalation, I'm aware of that but I'm not planning to fix it as it an edge case scenario that mostly occur during development only.
